# btrfs-snapsetup.conf

# Target user for /home paths
USER_CONFIG="todolinux"

# Main root subvolume
ROOT_SUBVOL="@rootfs"

# Top-level mount point (subvolid=5)
MNT_POINT="/mnt/btrfs_top"

# The subvolume name to set as default for booting
DEFAULT_SUBVOL_NAME="@rootfs"

# List of folders to be migrated into subvolumes
# You can add your own folder path to the list below
# /boot can not be removed
SUBVOL_DIRS=(
    "/boot"
    "/var"
    "/home"
    "/opt"
    "/root"
    "/usr/local"
    "/home/$USER_CONFIG/Videos"
    "/home/$USER_CONFIG/opencloud"
    "/home/$USER_CONFIG/Pictures"
    "/home/$USER_CONFIG/Nextcloud"
    "/home/$USER_CONFIG/Music"
    "/home/$USER_CONFIG/Downloads"
    "/home/$USER_CONFIG/.local/share/Trash"
    "/home/$USER_CONFIG/.cache/BraveSoftware"
    "/home/$USER_CONFIG/.config/BraveSoftware"
    "/home/$USER_CONFIG/.cache/thorium"
    "/home/$USER_CONFIG/.cache/spotify"
)

# File for logs
LOG_FILE="btrfs-snapsetup.log"

PROTECTED_SUBVOLS=("@boot" "@" "@rootfs")

FSTAB_OPTIONS=(
    "noatime"
    "compress=zstd"
)

ROOT_DEV="/dev/sda2"

EFI_DEV="/dev/sda1"
